#项目启动的端口
server:
  port: 8181
  servlet:
    #应用的访问路径
    context-path: /
spring:
  #数据库连接参数
  datasource:
      #mysql的驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      #数据库账号名
      username: tww
      #数据库密码
      password: tww1999
      #数据库连接url
      url: jdbc:mysql://localhost:3306/bookmanage?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    # redis相关配置
    # 对于单机版的Redis，可以使用此参数指定(数据库index),操作使用哪一个数据库
    # Redis支持多个数据库(默认是16个，可通过配置来修改数据库数量)，并且每个数据库的数据是隔离的，不能
    # 共享，并且基于单机才有，如果是集群就没有数据库的概念，集群只有一个db0数据库
  redis:
    # Redis服务器地址
    host: 192.168.43.68
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000
    database: 0
    #lettuce版本
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  cache:
    type: redis
    redis:
      # 定义超时时间 单位毫秒
      time-to-live: 600000

  rabbitmq:
    host: 192.168.43.68
    port: 5672
    username: admin
    password: admin

  # mybatis配置
mybatis:
  # mybatis配置，mapper.xml映射文件的路径
  mapper-locations: classpath:/mapper/*.xml


# pagehelper分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true #开启优化，<1页返回第一页
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql